### ISSUE TITLE
user_data missing from droplet_create

### ISSUE THREAD

**Issue by bvierra** [andrewalker/p5-webservice-digitalocean#3]
Hello,

The option for user_data is missing from droplet_create, this is a requirement to create a CoreOS box as you need to pass variables to the install.

It is a string and optional per (https://developers.digitalocean.com/#create-a-new-droplet)

**Comment by andrewalker** [comment]
Thanks for reporting this, @bvierra. I implemented it in d90bcf6. Can you confirm it fixes the problem?

**Comment by bvierra** [comment]
That appears to do it
