### ISSUE TITLE
Unexpected Content-Type error from UserAgent.pm

### ISSUE THREAD

**Issue by avtalley65** [andrewalker/p5-webservice-digitalocean#4]
When I use the Perl code below to send a key_create action, I get this error message: Unexpected Content-Type text/plain at /usr/local/share/perl/5.18.2/WebService/DigitalOcean/Role/UserAgent.pm line 100.

  my $response = $do->key_create({
        name            => "$kp_name",
        public_key      => "$pubkey",
  });
  my $kpid = $response->{content}{id};

I have verified that the content of both $kp_name and $pubkey are correct and properly formatted. I also get the same error when I try to create a droplet. I don't think I've made a mistake in my code, but...??

**Comment by andrewalker** [comment]
Thank you for your report, I'll take a look.

**Comment by avtalley65** [comment]
OK - whatever was causing my issue, it has gone away. Both actions are working just fine now. I don't know if you made any changes, but thanks nonetheless.
