### ISSUE TITLE
Content-Type warning on droplet_delete method

### ISSUE THREAD

**Issue by sestaton** [andrewalker/p5-webservice-digitalocean#6]
According to the [API documentation](https://developers.digitalocean.com/documentation/v2/#delete-a-droplet) the delete method now returns a Content-Type of 'application/octet-stream' whereas other methods return json, as expected. So, you get a warning when deleting a droplet:

```
Unexpected Content-Type  at /home/statonse/github/p5-webservice-digitalocean/lib/WebService/DigitalOcean/Role/UserAgent.pm line 100.
```

I'm not sure what would be the best way to fix this one but I thought it would be good to report. The method works fine, it just issues a warning.

**Comment by andrewalker** [comment]
Thank you for the report, I'll try and update it.

**Comment by sestaton** [comment]
An easy fix would be to check if the content-type is one of the two expected types. Another approach would be to check the content-type of specific requests against what is expected to be returned. The latter approach would require more code and it may be more fragile given that the API could change. If the first solution is satisfactory I could apply that and submit a pull request.

**Comment by sestaton** [comment]
I discovered that this issue can be resolved by simply checking the length of the content type string since it is blank with the delete method. I opened a new pull request with the change.

**Comment by sestaton** [comment]
Sorry for the multiple commits on the PR. Feel free to squash them and remove the `else {}` loop that was added (meant to remove it in the last commit). Really all that is necessary to resolve this is the `if length $content_type` check added to the warn statement.

**Comment by andrewalker** [comment]
No worries. Thanks for the patch, and sorry for taking so long to respond :)
