### ISSUE TITLE
Unexpected Content-Type text/plain

### ISSUE THREAD

**Issue by biannetta** [andrewalker/p5-webservice-digitalocean#8]
Getting the following error:

`Unexpected Content-Type text/plain at /Library/Perl/5.18/WebService/DigitalOcean/Role/UserAgent.pm line 100.`

This is the code that causes this:
```perl
my $do = WebService::DigitalOcean->new(token => $TOKEN);
my $response = $do->droplet_list();
for (@{ $response->{content} }) {
      print $_->{'id'}.": ".$_->{'name'}."\n";
}
```

**Comment by biannetta** [comment]
In case anyone is wondering, this is the response from the DigitalOcean API 

>Can't verify SSL peers without knowing which Certificate Authorities to trust

>This problem can be fixed by either setting the PERL_LWP_SSL_CA_FILE
envirionment variable or by installing the Mozilla::CA module.

>To disable verification of SSL peers set the PERL_LWP_SSL_VERIFY_HOSTNAME
envirionment variable to 0.  If you do this you can't be sure that you
communicate with the expected peer.

Installing the Mozilla::CA module resolved the issue

**Comment by andrewalker** [comment]
Oh, thanks for posting the solution.
I'm sorry I haven't been so responsive. I haven't been using the module for a while, and haven't had time to keep maintaining it.
But thanks again for creating the issue and later posting the solution! Hopefully it will be useful to others.
